### ISSUE TITLE
Async Handling Issue

### ISSUE THREAD

**Issue by ov-tron** [ov-sa/DBify-Library#3]
For async queries the conditional returns must always use callback otherwise the main thread remains frozen forever

**Comment by OvileAmriam** [comment]
Such as this for instance: https://github.com/ov-sa/DBify-Library/blob/master/module/DBify_Library/dep/module/inventory.lua#L71

**Comment by Anisa-Nur** [comment]
Resolved in the new release: https://github.com/ov-sa/DBify-Library/releases/tag/v.1.2.1
